### ISSUE TITLE
Can you offer another way to install gptcommit for Windows? Like, Winget

### ISSUE THREAD

**Issue by SinnoSong** [zurawiki/gptcommit#134]
**Is your feature request related to a problem? Please describe.**
In Windows I need install C++ build tools for cargo, then I can install gptcommit. In Mac you provider `brew` to install, can you offer Winget?

**Describe the solution you'd like**
Offer the way to install from Winget

**Describe alternatives you've considered**
Offer an `exe` file for Windows

**Additional context**

**Comment by SinnoSong** [comment]
I find the `gptcommit.exe` in my `~\.cargo\bin` directory, if copy this file to another Windows PC, should it work normally？

**Comment by zurawiki** [comment]
@SinnoSong Thanks for the feedback. I'm happy to support other options for installing these binaries but I don't have experience with Windows tooling. I'm happy to review a pull request. 

You can download the `*.exe` file from the releases page here:
https://github.com/zurawiki/gptcommit/releases/tag/v0.5.3

For Windows, look for the "gptcommit-x86_64-pc-windows-msvc.zip" file


Note that some new versions didn't come with artifacts, this was reported in #136 and should be fixed in v0.5.6
